### ISSUE TITLE
Download Version problem

### ISSUE THREAD

**Issue by DavisMillier** [corytodd/porty#2]
Hello 
I can not download your last source code 
May you check it ?

**Comment by corytodd** [comment]
How are you downloading? Git, zip, and release are all working fine...

**Comment by DavisMillier** [comment]
I try Download and Clone button
some file was missing in zip file
may you check it again ?
i try to know how can i auto Detect GPS plug to computer

**Comment by corytodd** [comment]
Runs fine for me so I'll need more information in order to help. Do you have any logs, errors, or screenshots?

**Comment by DavisMillier** [comment]
Severity	Code	Description	Project	File	Line
Error		Unable to find manifest signing certificate in the certificate store.	Porty		



and : Porty_TemporaryKey.pfx missing file

**Comment by corytodd** [comment]
Thank you, I see the problem. I just pushed the fix.
